export const trafficData = [
  {
    id: "req-001",
    method: "GET",
    url: "https://api.securityhub.example.com/auth/status",
    status: 200,
    time: "120ms",
    protocol: "HTTP/2",
    headers: {
      Host: "api.securityhub.example.com",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      Accept: "application/json",
      Authorization: "Bearer eyJhbGci...",
    },
    body: "",
    response: {
      status: 200,
      statusText: "OK",
      headers: {
        "content-type": "application/json;charset=UTF-8",
        "cache-control": "no-store",
      },
      body: '{"status":"authorized","session":"active"}',
    },
  },
  {
    id: "req-002",
    method: "POST",
    url: "https://admin.cyberintercept.io/api/login",
    status: 403,
    time: "98ms",
    protocol: "HTTP/1.1",
    headers: {
      Host: "admin.cyberintercept.io",
      "User-Agent": "curl/8.4.1",
      "Content-Type": "application/x-www-form-urlencoded",
      Accept: "*/*",
    },
    body: "username=admin&password=secret",
    response: {
      status: 403,
      statusText: "Forbidden",
      headers: {
        "content-type": "application/json",
        "www-authenticate": "Bearer realm=\"CyberIntercept\"",
      },
      body: '{"error":"Access denied","code":403}',
    },
  },
  {
    id: "req-003",
    method: "PATCH",
    url: "https://device.example.net/api/settings/alerts",
    status: 200,
    time: "140ms",
    protocol: "HTTP/2",
    headers: {
      Host: "device.example.net",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5)",
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: '{"alerts":false}',
    response: {
      status: 200,
      statusText: "OK",
      headers: {
        "content-type": "application/json",
        "cache-control": "max-age=0",
      },
      body: '{"message":"settings updated","alerts":false}',
    },
  },
  {
    id: "req-004",
    method: "DELETE",
    url: "https://api.corp.example.com/v1/sessions/823",
    status: 401,
    time: "112ms",
    protocol: "HTTP/1.1",
    headers: {
      Host: "api.corp.example.com",
      "User-Agent": "PostmanRuntime/7.33.0",
      Accept: "*/*",
      Authorization: "Basic YWRtaW46cGFzc3dvcmQ=",
    },
    body: "",
    response: {
      status: 401,
      statusText: "Unauthorized",
      headers: {
        "content-type": "application/json",
        "www-authenticate": "Basic realm=\"API\"",
      },
      body: '{"message":"Authentication required"}',
    },
  },
  {
    id: "req-005",
    method: "PUT",
    url: "https://gateway.example.com/api/password",
    status: 204,
    time: "186ms",
    protocol: "HTTP/1.1",
    headers: {
      Host: "gateway.example.com",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64)",
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: '{"password":"new-password"}',
    response: {
      status: 204,
      statusText: "No Content",
      headers: {
        "content-type": "application/json",
      },
      body: "",
    },
  },
  {
    id: "req-006",
    method: "GET",
    url: "https://auth.example.io/api/users?limit=20",
    status: 200,
    time: "74ms",
    protocol: "HTTP/2",
    headers: {
      Host: "auth.example.io",
      "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)",
      Accept: "application/json",
      Authorization: "Bearer eyJhbGci...",
    },
    body: "",
    response: {
      status: 200,
      statusText: "OK",
      headers: {
        "content-type": "application/json",
        "cache-control": "no-cache",
      },
      body: '{"users":[{"id":11,"name":"Ava"},{"id":12,"name":"Noah"}]}',
    },
  },
];
